### ISSUE TITLE
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\framework\ops.py", line 6649, in __init__     raise ValueError("name for name_scope must be a string.")

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#146] opened 2023-04-24 06:22 UTC
Hi, I have a weird problem. I used the same dataset and parameters to run dannce-predict. However, the result was good one month ago; but now I cannot reduplicate the same result but always meet the error as below. Has anyone also got the same problem? Thank you @spoonsso @davidhildebrand 

`(tfnew_25) F:\dannce\demo\mouse6169>dannce-predict .\dannce_mouse_config_6169.yaml
2023-04-24 14:12:07.568290: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
io_config not found in io.yaml file, falling back to main config
new_n_channels_out not found in io.yaml file, falling back to main config
downfac not found in io.yaml file, falling back to main config
extension not found in io.yaml file, falling back to main config
batch_size not found in io.yaml file, falling back to main config
n_views not found in io.yaml file, falling back to main config
mono not found in io.yaml file, falling back to main config
debug not found in io.yaml file, falling back to main config
epochs not found in io.yaml file, falling back to main config
net_type not found in io.yaml file, falling back to main config
verbose not found in io.yaml file, falling back to main config
train_mode not found in io.yaml file, falling back to main config
num_validation_per_exp not found in io.yaml file, falling back to main config
vol_size not found in io.yaml file, falling back to main config
nvox not found in io.yaml file, falling back to main config
dannce_finetune_weights not found in io.yaml file, falling back to main config
predict_mode not found in io.yaml file, falling back to main config
com_train_dir set to: .\COM\train_results\
com_predict_dir set to: .\COM\predict_results\
dannce_train_dir set to: .\DANNCE\train_results\MAX\
dannce_predict_dir set to: .\DANNCE\predict_results\
exp set to: [{'label3d_file': 'F:\\dannce\\demo\\mouse6169\\label3d_6169_3h_com_dannce.mat'}]
io_config set to: io.yaml
new_n_channels_out set to: 16
downfac set to: 2
extension set to: .avi
batch_size set to: 1
n_views set to: 5
mono set to: True
debug set to: True
epochs set to: 1200
net_type set to: MAX
verbose set to: 1
train_mode set to: finetune
num_validation_per_exp set to: 0
vol_size set to: 240
nvox set to: 80
dannce_finetune_weights set to: F:\dannce\weight\MAX5\
predict_mode set to: torch
base_config set to: .\dannce_mouse_config_6169.yaml
viddir set to: videos
crop_height set to: None
crop_width set to: None
camnames set to: None
n_channels_out set to: 20
sigma set to: 10
net set to: None
gpu_id set to: 0
immode set to: vid
mirror set to: False
max_num_samples set to: None
start_batch set to: 0
start_sample set to: None
com_fromlabels set to: False
medfilt_window set to: None
com_file set to: None
new_last_kernel_size set to: [3, 3, 3]
n_layers_locked set to: 2
vmin set to: None
vmax set to: None
interp set to: nearest
depth set to: False
comthresh set to: 0
weighted set to: False
com_method set to: median
cthresh set to: None
channel_combo set to: None
dannce_predict_model set to: None
expval set to: None
from_weights set to: None
write_npy set to: None
loss set to: mask_nan_keep_loss
n_channels_in set to: None
vid_dir_flag set to: None
num_train_per_exp set to: None
chunks set to: None
lockfirst set to: None
load_valid set to: None
augment_hue set to: False
augment_brightness set to: False
augment_hue_val set to: 0.05
augment_bright_val set to: 0.05
augment_rotation_val set to: 5
drop_landmark set to: None
raw_im_h set to: None
raw_im_w set to: None
n_instances set to: 1
use_npy set to: False
data_split_seed set to: None
valid_exp set to: None
metric set to: ['euclidean_distance_3D']
lr set to: 0.001
rotate set to: True
augment_continuous_rotation set to: False
com_thresh set to: None
cam3_train set to: None
debug_volume_tifdir set to: None
dannce_predict_vol_tifdir set to: None
n_rand_views set to: 0
rand_view_replace set to: True
multi_gpu_train set to: False
heatmap_reg set to: False
heatmap_reg_coeff set to: 0.01
save_pred_targets set to: False
Using the following *dannce.mat files: .\label3d_6169_3h_com_dannce.mat
Setting vid_dir_flag to True.
Setting extension to .avi.
Setting chunks to {'Camera1': array([], dtype=float64), 'Camera2': array([], dtype=float64), 'Camera3': array([], dtype=float64), 'Camera4': array([], dtype=float64), 'Camera5': array([], dtype=float64)}.
Traceback (most recent call last):
  File "E:\anaconda\envs\tfnew_25\Scripts\dannce-predict-script.py", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-predict')())
  File "f:\dannce\dannce\cli.py", line 53, in dannce_predict_cli
    params = build_clarg_params(args, dannce_net=True, prediction=True)
  File "f:\dannce\dannce\cli.py", line 87, in build_clarg_params
    params = infer_params(params, dannce_net, prediction)
  File "f:\dannce\dannce\engine\processing.py", line 126, in infer_params
    camf = os.path.join(viddir, video_files[0])
IndexError: list index out of range

(tfnew_25) F:\dannce\demo\mouse6169>dannce-predict .\dannce_mouse_config_6169.yaml
2023-04-24 14:15:56.229279: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
io_config not found in io.yaml file, falling back to main config
new_n_channels_out not found in io.yaml file, falling back to main config
downfac not found in io.yaml file, falling back to main config
extension not found in io.yaml file, falling back to main config
batch_size not found in io.yaml file, falling back to main config
n_views not found in io.yaml file, falling back to main config
mono not found in io.yaml file, falling back to main config
debug not found in io.yaml file, falling back to main config
epochs not found in io.yaml file, falling back to main config
net_type not found in io.yaml file, falling back to main config
verbose not found in io.yaml file, falling back to main config
train_mode not found in io.yaml file, falling back to main config
num_validation_per_exp not found in io.yaml file, falling back to main config
vol_size not found in io.yaml file, falling back to main config
nvox not found in io.yaml file, falling back to main config
dannce_finetune_weights not found in io.yaml file, falling back to main config
predict_mode not found in io.yaml file, falling back to main config
com_train_dir set to: .\COM\train_results\
com_predict_dir set to: .\COM\predict_results\
dannce_train_dir set to: .\DANNCE\train_results\MAX\
dannce_predict_dir set to: .\DANNCE\predict_results\
exp set to: [{'label3d_file': 'F:\\dannce\\demo\\mouse6169\\label3d_6169_3h_com_dannce.mat'}]
io_config set to: io.yaml
new_n_channels_out set to: 16
downfac set to: 2
extension set to: .avi
batch_size set to: 1
n_views set to: 5
mono set to: True
debug set to: True
epochs set to: 1200
net_type set to: MAX
verbose set to: 1
train_mode set to: finetune
num_validation_per_exp set to: 0
vol_size set to: 240
nvox set to: 80
dannce_finetune_weights set to: F:\dannce\weight\MAX5\
predict_mode set to: torch
base_config set to: .\dannce_mouse_config_6169.yaml
viddir set to: videos
crop_height set to: None
crop_width set to: None
camnames set to: None
n_channels_out set to: 20
sigma set to: 10
net set to: None
gpu_id set to: 0
immode set to: vid
mirror set to: False
max_num_samples set to: None
start_batch set to: 0
start_sample set to: None
com_fromlabels set to: False
medfilt_window set to: None
com_file set to: None
new_last_kernel_size set to: [3, 3, 3]
n_layers_locked set to: 2
vmin set to: None
vmax set to: None
interp set to: nearest
depth set to: False
comthresh set to: 0
weighted set to: False
com_method set to: median
cthresh set to: None
channel_combo set to: None
dannce_predict_model set to: None
expval set to: None
from_weights set to: None
write_npy set to: None
loss set to: mask_nan_keep_loss
n_channels_in set to: None
vid_dir_flag set to: None
num_train_per_exp set to: None
chunks set to: None
lockfirst set to: None
load_valid set to: None
augment_hue set to: False
augment_brightness set to: False
augment_hue_val set to: 0.05
augment_bright_val set to: 0.05
augment_rotation_val set to: 5
drop_landmark set to: None
raw_im_h set to: None
raw_im_w set to: None
n_instances set to: 1
use_npy set to: False
data_split_seed set to: None
valid_exp set to: None
metric set to: ['euclidean_distance_3D']
lr set to: 0.001
rotate set to: True
augment_continuous_rotation set to: False
com_thresh set to: None
cam3_train set to: None
debug_volume_tifdir set to: None
dannce_predict_vol_tifdir set to: None
n_rand_views set to: 0
rand_view_replace set to: True
multi_gpu_train set to: False
heatmap_reg set to: False
heatmap_reg_coeff set to: 0.01
save_pred_targets set to: False
Using the following *dannce.mat files: .\label3d_6169_3h_com_dannce.mat
Setting vid_dir_flag to True.
Setting extension to .avi.
Setting chunks to {'Camera1': array([     0, 100800, 201600, 302400, 403200, 504000]), 'Camera2': array([     0, 100800, 201600, 302400, 403200, 504000]), 'Camera3': array([     0, 100800, 201600, 302400, 403200, 504000]), 'Camera4': array([     0, 100800, 201600, 302400, 403200, 504000]), 'Camera5': array([     0, 100800, 201600, 302400, 403200, 504000])}.
Setting n_channels_in to 3.
Setting raw_im_h to 2560.
Setting raw_im_w to 2560.
Setting expval to False.
Setting net to finetune_MAX.
Setting crop_height to [0, 2560].
Setting crop_width to [0, 2560].
Setting maxbatch to max.
Setting start_batch to 0.
Setting vmin to -120.0.
Setting vmax to 120.0.
Using the following *dannce.mat files: .\label3d_6169_3h_com_dannce.mat
Using torch predict mode
Using camnames: ['Camera1', 'Camera2', 'Camera3', 'Camera4', 'Camera5']
Experiment 0 using com3d: .\label3d_6169_3h_com_dannce.mat
Removed 0 samples from the dataset because they either had COM positions over cthresh, or did not have matching sampleIDs in the COM file
Saving 3D COM to .\DANNCE\predict_results\com3d_used.mat
None
2023-04-24 14:16:19.833021: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-24 14:16:19.938893: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2023-04-24 14:16:19.939184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:41:00.0 name: NVIDIA GeForce RTX 3080 computeCapability: 8.6
coreClock: 1.8GHz coreCount: 68 deviceMemorySize: 10.00GiB deviceMemoryBandwidth: 707.88GiB/s
2023-04-24 14:16:19.939465: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2023-04-24 14:16:19.939655: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll2023-04-24 14:16:19.939765: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2023-04-24 14:16:19.939993: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll 
2023-04-24 14:16:19.941584: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll2023-04-24 14:16:19.946620: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2023-04-24 14:16:19.946881: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2023-04-24 14:16:19.947037: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll  
2023-04-24 14:16:19.947172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2023-04-24 14:16:20.366398: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-04-24 14:16:20.366705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2023-04-24 14:16:20.366880: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2023-04-24 14:16:20.367169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4607 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:41:00.0, compute capability: 8.6)
2023-04-24 14:16:20.376233: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set        
Init took 30.93600106239319 sec.
Initializing Network...
Loading model from .\DANNCE\train_results\MAX\weights.663-0.00005.hdf5
2023-04-24 14:16:51.388114: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
Traceback (most recent call last):
  File "E:\anaconda\envs\tfnew_25\Scripts\dannce-predict-script.py", line 33, in <module>
    sys.exit(load_entry_point('dannce', 'console_scripts', 'dannce-predict')())
  File "f:\dannce\dannce\cli.py", line 54, in dannce_predict_cli
    dannce_predict(params)
  File "f:\dannce\dannce\interface.py", line 1534, in dannce_predict
    "centered_euclidean_distance_3D": losses.centered_euclidean_distance_3D,
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\saving\save.py", line 207, in load_model
    compile)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 200, in load_model_from_hdf5
    training_config, custom_objects))
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\training\tracking\base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 453, in compile
    masks=self._prepare_output_masks())
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1973, in _handle_metrics
    target, output, output_mask))
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 1921, in _handle_per_output_metrics   
    with K.name_scope(metric_name):
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\keras\backend.py", line 935, in name_scope
    return ops.name_scope_v2(name)
  File "E:\anaconda\envs\tfnew_25\lib\site-packages\tensorflow\python\framework\ops.py", line 6649, in __init__
    raise ValueError("name for name_scope must be a string.")
ValueError: name for name_scope must be a string.`

**Comment by spoonsso** [comment] 2023-05-03 14:22
Duplicate of #147? Can continue discussion there.

**Closed as completed by spoonsso** 2023-05-03 14:22 UTC
